ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(common-aliases git gitfast history-substring-search last-working-dir macos vscode zsh-syntax-highlighting)

export HOMEBREW_NO_ANALYTICS=1

source "${ZSH}/oh-my-zsh.sh"
unalias rm

type -a mise > /dev/null && eval "$(mise activate zsh)"

export PATH="$HOME/.local/bin:${PATH}"

[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

export LANG=en_US.UTF-8

export EDITOR="code --wait"
export BUNDLER_EDITOR="code --wait"
